# Site settings
title: Jared Cunha — Washington, D.C. Product Designer
email: jaredcunha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jared Cunha is a senior product designer from the mighty city of Washington, D.C.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaredcunha.com" # the base hostname & protocol for your site
twitter_username: jaredcunha
github_username:  jaredcunha
permalink: /blog/:year/:month/:title

# Build settings
markdown: kramdown
highlighter: pygments
sass:
    sass_dir: /_assets/stylesheets/
exclude:      [/node_modules/, gulpfile.js, Gemfile, Gemfile.lock, npm-debug.log]
